version: '3.8'

services:
  db:
    platform: linux/amd64    # Use ARM64 variant on Apple Silicon
    image: postgis/postgis:17-3.5
    container_name: sanayi-db
    environment:
      POSTGRES_DB: sanayi
      POSTGRES_USER: sanayi_user
      POSTGRES_PASSWORD: furkan
    ports:
      - "25432:5432"
    volumes:
      - sanayi-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sanayi_user -d sanayi" ]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  sanayi-data: {}
