app:
  jwt:
    secret: "7b31f90fa4f5b4eedf99e8335df47a8573faeb071f54bab36349a291292beb89"
    expiration-ms: 86400000  # 1 gün
  cors:
    origins: http://localhost:3000,https://sanayi.dev
  recaptcha:
    enabled: false
    secret: "${RECATPCHA_SECRET}"
  ratelimit:
    enabled: true
    perMinute: 30

spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/sanayi
    username: sanayi_user
    password: furkan
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    #placeholder-replacement: true
    #baseline-on-migrate: true #Elinde hali hazırda tablolar varsa, baseline-on-migrate: true doğru; ama gerçekten yeni bir DB’de ilk kez migration koşacaksan bu satırı kaldırıp en baştan V1’den başlamak da yeterli.
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000, expireAfterWrite=10m
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

